/**
 * Optimization plan domain types for the GridWise energy-optimization challenge.
 *
 * These types represent the output of the optimization pipeline:
 *   - HourlyPlanEntry: the per-hour decision produced by the solver
 *   - OptimizationPlan: the complete 24-hour plan with aggregates
 *   - OptimizationResponse: the full API response body
 *
 * Source of truth:
 *   - BUP_CSE_FEST_2026_Preli_Public_Sample_Cases.json
 *     (schema_notes.output_required_fields, hourly_plan_required_fields,
 *      allowed_enums.battery_action)
 *   - docs/roadmap.md Phase 1 (OptimizationPlan fields)
 *
 * Ownership:
 *   - Teammate A defines these types (domain contract).
 *   - Teammate C (optimizer/solver) produces HourlyPlanEntry[] and the
 *     aggregate values.
 *   - Teammate D (schedule validator) replays the plan and recalculates
 *     total_grid_kwh, total_cost_bdt, peak_grid_kwh independently.
 *   - Teammate A wraps OptimizationPlan in the HTTP response.
 */

import type { DirectiveInterpretationList } from "./directive.ts";

// ---------------------------------------------------------------------------
// Battery action enum
// ---------------------------------------------------------------------------

/**
 * The battery action taken during a given hour.
 * Exactly one of the three values from the challenge allowed_enums.
 */
export type BatteryAction = "charge" | "discharge" | "idle";

// ---------------------------------------------------------------------------
// Per-hour plan entry
// ---------------------------------------------------------------------------

/**
 * The solver's decision for a single hour.
 *
 * Energy balance invariant (must hold for every hour):
 *   grid_kwh + solar_used_kwh + battery_discharge_kwh = demand_kwh + battery_charge_kwh
 *
 * Where battery_discharge_kwh and battery_charge_kwh are derived from
 * battery_action and battery_kwh:
 *   - action "charge":    battery_charge_kwh = battery_kwh, discharge = 0
 *   - action "discharge": battery_discharge_kwh = battery_kwh, charge = 0
 *   - action "idle":      battery_kwh = 0, charge = 0, discharge = 0
 *
 * Field names match the challenge's hourly_plan_required_fields exactly.
 */
export interface HourlyPlanEntry {
  /** Hour index in [0, 23]. */
  readonly hour: number;
  /** Grid electricity imported this hour (kWh). Must be >= 0. */
  readonly grid_kwh: number;
  /**
   * Solar energy actually used this hour (kWh).
   * Must be <= effective solar (after solar_reduction directives).
   */
  readonly solar_used_kwh: number;
  /** Whether the battery is charging, discharging, or idle. */
  readonly battery_action: BatteryAction;
  /**
   * Energy charged to or discharged from the battery this hour (kWh).
   * Always >= 0; direction is given by battery_action.
   * Must be 0 when battery_action is "idle".
   */
  readonly battery_kwh: number;
  /**
   * Battery state of charge at the end of this hour (kWh).
   * Must satisfy: minimum_energy_kwh <= battery_energy_after_kwh <= capacity_kwh
   * For hour 23: must equal Scenario.battery.initial_energy_kwh
   *   (end-of-day neutrality).
   */
  readonly battery_energy_after_kwh: number;
}

// ---------------------------------------------------------------------------
// Complete optimization plan
// ---------------------------------------------------------------------------

/**
 * The full 24-hour optimization plan produced by the solver.
 *
 * Aggregate values (total_grid_kwh, total_cost_bdt, peak_grid_kwh) must be
 * recalculated from hourly_plan by the independent schedule validator —
 * they are not trusted from the optimizer directly.
 */
export interface OptimizationPlan {
  /**
   * Exactly 24 entries, one per hour, ordered by hour 0..23.
   */
  readonly hourly_plan: readonly HourlyPlanEntry[];
  /** Sum of grid_kwh across all 24 hours. */
  readonly total_grid_kwh: number;
  /**
   * Total grid electricity cost in BDT.
   * Calculated as: Σ (grid_kwh[h] × tariff_bdt_per_kwh[h]) for h in 0..23
   */
  readonly total_cost_bdt: number;
  /**
   * The highest single-hour grid import across the 24-hour window (kWh).
   * Calculated as: max(grid_kwh[h]) for h in 0..23
   */
  readonly peak_grid_kwh: number;
  /**
   * A short human-readable description of the optimization strategy used.
   * Generated by the optimizer or composed from directive context.
   */
  readonly plan_summary: string;
}

// ---------------------------------------------------------------------------
// Full API response body
// ---------------------------------------------------------------------------

/**
 * The complete response returned by POST /optimize-energy.
 *
 * Field names and presence match the challenge's output_required_fields exactly:
 *   scenario_id, directive_interpretation, hourly_plan,
 *   total_grid_kwh, total_cost_bdt, peak_grid_kwh, plan_summary
 *
 * Note: the flat structure (not nested under "data") matches the challenge
 * spec. The Hono route wraps this in the repo's { data: ... } envelope.
 */
export interface OptimizationResponse {
  /** Echo of the input scenario_id. */
  readonly scenario_id: string;
  /**
   * One interpretation per operator note, ordered by note_index.
   * Length equals Scenario.operator_notes.length.
   */
  readonly directive_interpretation: DirectiveInterpretationList;
  /** The 24-hour hourly plan. */
  readonly hourly_plan: readonly HourlyPlanEntry[];
  /** Total grid consumption (kWh) across all 24 hours. */
  readonly total_grid_kwh: number;
  /** Total grid electricity cost (BDT) across all 24 hours. */
  readonly total_cost_bdt: number;
  /** Peak single-hour grid import (kWh). */
  readonly peak_grid_kwh: number;
  /** Short narrative summary of the optimization strategy. */
  readonly plan_summary: string;
}
